#!/bin/bash
set -euxo pipefail

cd "$(dirname "$0")"

test -t 0 && sudo -v

export XDG_CONFIG_HOME=~/.config
export XDG_CACHE_HOME=~/.cache
export XDG_DATA_HOME=~/.local
export XDG_STATE_HOME=~/.local/state

mkdir -p ~/.config ~/.cache ~/.local/share ~/.local/state
ln -s ~/dotfiles/chezmoi ~/.local/share/chezmoi
git clone https://github.com/asdf-vm/asdf.git ~/.asdf
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install shellcheck chezmoi elvish starship gh ripgrep
echo "Please do '/usr/local/bin/elvish >> /etc/shells and chsh -s /usr/local/bin/elvish'"
brew install --cask wezterm

nerd_fonts() {
  git clone --branch=master --depth=1 https://github.com/ryanoasis/nerd-fonts.git
  cd nerd-fonts
  ./install.sh $1
  cd ..
  rm -rf nerd-fonts
}

nerd_fonts SpaceMono

export PATH=~/.asdf/bin:~/.asdf/shims:$PATH
asdf plugin add direnv
asdf install direnv latest
asdf global direnv latest
asdf plugin add chezmoi
asdf install chezmoi latest
asdf global chezmoi latest

exit 0
