name: DOTFILES CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Test setup scripts
      run: ./setup
    - name: Run shellcheck
      run: ./ci

